_target_: src.data.data_module.DataModule
dataset_name: public
df_path: /kaggle/working/processed/processed_df.csv
batch_size: 64
num_workers: 2
pin_memory: true
splits: None
train_transforms:
  _target_: src.data.augmentations.Augmentations
  config:
    aug_list:
valid_transforms:
  _target_: src.data.augmentations.Augmentations
  config:
    aug_list:
